<div id="stickyHeader">
	<ul id="mainNav">
		<li id="logo">
			<a href="#header"><img src="images/ar-logo.png" id="logo" /></a>
		</li>
		<li>
			<a href="#bio">Biography</a>
		</li>
		<li>
			<a href="#portfolio">Portfolio</a>
		</li>
		<li>
			<a href="#resume">Resume</a>
		</li>
		<li>
			<a href="#contact">Contact</a>
		</li>
	</ul>
</div>
<div id="mock-scroller"></div>
<div id="content">
