<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>AR Portfolio</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="copyright" content="2013 AndiRuda All Rights Reserved" /> 
    <meta name="author" content="AndiRuda" /> 
    <meta name="city" content="" /> 
    <meta name="country" content="" /> 
    <meta name="Distribution" content="Global" /> 
    <meta name="Rating" content="General" /> 
    <meta name="Robots" content="INDEX,FOLLOW" />
    
    <link rel="stylesheet" type="text/css" href="css/custom.css" media="screen" />
	 <link href="http://fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet" type="text/css" />
    <!--[if IE 6]>
		<link rel="stylesheet" type="text/css" href="css/ie6.css" media="screen" />
	<![endif]-->
	<!--[if IE 7]>
		<link rel="stylesheet" type="text/css" href="css/ie7.css" media="screen" />
	<![endif]-->
	<!--[if IE 8]>
		<link rel="stylesheet" type="text/css" href="css/ie8.css" media="screen" />
	<![endif]-->
	<!--[if IE 9]>
		<link rel="stylesheet" type="text/css" href="css/ie9.css" media="screen" />
	<![endif]-->
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>    
	
	<!--Slice Box 
	<link rel="stylesheet" type="text/css" href="js/slicebox/css/slicebox.css" />
	<link rel="stylesheet" type="text/css" href="js/slicebox/css/custom.css" />
	<script type="text/javascript" src="js/slicebox/js/modernizr.custom.46884.js"></script>
	<script type="text/javascript" src="js/slicebox/js/jquery.slicebox.js"></script>
	-->
	
	<!-- Polaroid -->
    <script type="text/javascript" src="js/polaroid/polaroid.js"></script>
	<link rel="stylesheet" type="text/css" href="js/polaroid/polaroid.css" media="screen" />

	<!-- Colorbox -->
	<link rel="stylesheet" href="js/colorbox/colorbox.css" />
	<script src="js/colorbox/jquery.colorbox.js"></script>	

	<!-- parallax -->
	<link href="js/parallax/css/reset.css"  rel="stylesheet" type="text/css" />
	<link href="js/parallax/css/chrome.css" rel="stylesheet" type="text/css" />
	<!--<link href="js/css/demo1.css"     rel="stylesheet" type="text/css" />-->

	<!--[if lt IE 9]>
		<script src="js/html5.js"></script>
	<![endif]-->

	<!--<script type="text/javascript" src="js/parallax/js/jquery-1.7.1.js"          ></script>-->
	<script type="text/javascript" src="js/parallax/js/side-nav.js"              ></script>
	<script type="text/javascript" src="js/parallax/js/backgrounds.js"           ></script>
	<script type="text/javascript" src="js/parallax/js/kinetics.js"              ></script>

	<!-- parallax.js really screws with the DOM, so make sure it's included last so other things dont notice :) -->
	<script type="text/javascript" src="/js/parallax/js/parallax.js"></script>
	


